version: "3.7"
services:
  nginx:
    image: nginx:1.21.5
    networks:
      - network
    volumes:
      - /home/juchan015326/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_gunicorn:
    image: django-image:3
    networks:
      - network
    volumes:
      - static-volume:/home/ubuntu/SoriDam/static
      - media-volume:/home/ubuntu/SoriDam/media

networks:
  network:

volumes:
  static-volume:
  media-volume:
